# Generated by Django 2.2.19 on 2021-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_enfermedad_userfullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubiculo', models.IntegerField()),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratorio', models.IntegerField()),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.IntegerField()),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
